version: "3.8"
services:
  app:
    platform: linux/arm64/v8
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb?schema=public
      - NODE_ENV=development
      - PORT=8000
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USER=test@example.com
      - SMTP_PASSWORD=test
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run dev"

  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    platform: linux/amd64
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
